### PR TITLE
ARM64 support

### PR DESCRIPTION
**Pull request by mark-mb**
This changes allow OpenMM to compile and run the tests in an A72 platform. Discussion for further work in #2618

### CODE REVIEW

**Comment by peastman** [comment]
@jaimergp could you take a look at this and make sure it looks ok?

**Comment by peastman** [comment]
Could you comment on the changes to JAMA?  I get very nervous about changes to complex numerical libraries that I don't understand!  Are these changes that should be contributed to the upstream package?

**Comment by jaimergp** [comment]
Let's see if the CF build works with these changes!

**Comment by jaimergp** [comment]
> Could you comment on the changes to JAMA? I get very nervous about changes to complex numerical libraries that I don't understand! Are these changes that should be contributed to the upstream package?

According to the commit message: "This was already present in JAMA 1.0.3, but not in OpenMM"

**Comment by peastman** [comment]
In that case, shall we just update to the latest version of JAMA?

**Comment by jaimergp** [comment]
I guess there are no downsides to that!

**Comment by mark-mb** [comment]
> Could you comment on the changes to JAMA? I get very nervous about changes to complex numerical libraries that I don't understand! Are these changes that should be contributed to the upstream package?

One of the tests was stuck in an infinite loop because JAMA::SVC wasn't converging. It was comparing something like 1e-324 to 0, which, of course, are different. The solution in these cases is usually to add some wiggle room, but, like you, I wouldn't be comfortable just changing it.

I checked latest JAMA version source (latest, meaning November 2012), and there was that same "tiny" variable set to pow(2, -966). In the C++ version, I set it to the smallest representable double possible. That fixed the issue, and the test passed.

**Comment by peastman** [comment]
In that case, how about if we remove those changes from this PR, and then in a separate PR update to the latest JAMA version?  I feel better about just keeping in sync with the standard package.

**Comment by mark-mb** [comment]
I'll do that. Is JAMA code somewhere directly in C++, or do I have to translate it from Java to C++?

**Comment by peastman** [comment]
It's at https://math.nist.gov/tnt/download.html.

**Comment by jaimergp** [comment]
That indeed worked! https://cloud.drone.io/conda-forge/openmm-feedstock/13/1/2

**Comment by mark-mb** [comment]
I moved the JAMA changes to openmm#2626.

The Jenkins failures in this pull request seem unrelated to the patch. Not sure what procedure you usually follow in these cases.

**Comment by peastman** [comment]
Thank you!

**Pull request merged**
