### PR TITLE
Fix M1 CI

### PR DESCRIPTION
**Pull request by mikemhenry**
Going to work on fixing the M1 CI with this one!

### CODE REVIEW

**Comment by mikemhenry** [comment]
@peastman M1 is working now (as a runner) but we have some failing tests:

```
The following tests FAILED:
	100 - TestSerializeNoseHooverIntegrator (SEGFAULT)
	104 - TestSerializeState (SEGFAULT)
Errors while running CTest
Test project /Users/lilmac/Projects/GH-Runner/actions-runner/_work/openmm/openmm/build
    Start 100: TestSerializeNoseHooverIntegrator
    Start 104: TestSerializeState
1/2 Test #100: TestSerializeNoseHooverIntegrator ...***Exception: SegFault  0.00 sec

2/2 Test #104: TestSerializeState ..................***Exception: SegFault  0.00 sec


0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.01 sec

The following tests FAILED:
	100 - TestSerializeNoseHooverIntegrator (SEGFAULT)
	104 - TestSerializeState (SEGFAULT)
Errors while running CTest
******************************
Rerunning failing tests...
******************************
```

Looks like some nasty segfault that happens so fast, we get no output, any ideas?

**Comment by peastman** [comment]
Strange.  Both those tests pass for me on my M1 Pro laptop.

Since you have direct access to the computer it runs on, are you able to preserve the build artifacts?  If so, the next step would be to run the failing tests in `lldb` to see where the segfault happens.

**Comment by jchodera** [comment]
It might be worth monitoring progress on the official M1 GitHub Actions runner support, which seems to be getting close:
https://github.com/actions/runner/issues/805

**Comment by mikemhenry** [comment]
That will be nice and help remove some of the hacks, but the good news/bad news is the errors are not coming from the self-hosted runner bits, but conda right now:

```
  Encountered problems while solving:
    - nothing provides ncurses >=6.2,<6.3.0a0 needed by libedit-3.1.20191231-hc8eb9b7_2
    - nothing provides ncurses >=6.2,<6.3.0a0 needed by libedit-3.1.20191231-hc8eb9b7_2
    - nothing provides ncurses >=6.2,<6.3.0a0 needed by libedit-3.1.20191231-hc8eb9b7_2
    - nothing provides ncurses >=6.2,<6.3.0a0 needed by libedit-3.1.20191231-hc8eb9b7_2
    - nothing provides ncurses >=6.2,<6.3.0a0 needed by libedit-3.1.20191231-hc8eb9b7_2
    - nothing provides ncurses >=6.2,<6.3.0a0 needed by libedit-3.1.20191231-hc8eb9b7_2
  
  The environment can't be solved, aborting the operation
  Warning: error    Could not solve for environment specs
  
  error    Could not solve for environment specs
  Warning: critical UnsatisfiableError
  
  critical UnsatisfiableError
```

I'm going to try switching to a different installer base to see if that helps.

@peastman Would it be okay if I split the M1 action into a separate yaml file? Then I could specify a default shell and avoid this ugliness to do steps only on the M1:

``` yaml
      - uses: conda-incubator/setup-miniconda@v2
        name: "Prepare base dependencies (M1)"
        if: matrix.os == 'M1-arm64'
        with:
          python-version: ${{ matrix.python-version }}
          installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Mambaforge-MacOSX-arm64.sh#${{ github.run_number }}
          #installer-url: https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh#${{ github.run_number }}
          environment-file: devtools/ci/gh-actions/conda-envs/build-${{ matrix.os }}.yml
          auto-activate-base: false

      - uses: conda-incubator/setup-miniconda@v2
        name: "Prepare base dependencies"
        if: matrix.os != 'M1-arm64'
        with:
          python-version: ${{ matrix.python-version }}
          activate-environment: build
          environment-file: devtools/ci/gh-actions/conda-envs/build-${{ matrix.os }}.yml
          auto-activate-base: false
```

**Comment by peastman** [comment]
Sure, if that makes it easier it's fine.

**Comment by jchodera** [comment]
Is anything further needed to fix `osx` support for M1/M2? This would be important for the beta.

**Comment by mikemhenry** [comment]
Getting the CI working is on my todo list, OSX isn't a very friendly to run as a headless server... There are a few options and settings that you can't change via CLI, and must log into the GUI. One way this CI breaks is after the server reboots, I have to log in the GUI in order for the permissions to "work" to allow the runner to reach github. I should have time to work on this soon

**Comment by jchodera** [comment]
@mikemhenry : GitHub just released a version of the [GitHub Actions Runner with Apple M1 support](https://github.blog/changelog/2022-08-09-github-actions-self-hosted-runners-now-support-apple-m1-hardware/) a few days ago! Would it be possible to update to use this?

**Comment by mikemhenry** [comment]
@jchodera Yes! When I hacked the runner together, I didn't do it the best way (it was a hack). I'm right now working on a solution that will make each job happen in an ephemeral environment so everything stays nice and clean (and will make it easier to use org wide)

**Comment by peastman** [comment]
Closing this PR since it's obsolete.

**Pull request closed without merging**
