### PR TITLE
CPU: Added support for AVX2.

### PR DESCRIPTION
**Pull request by dwtowner**

### CODE REVIEW

**Comment by peastman** [comment]
It looks like this produces build failures on Windows, as well as on ARM and PPC.

**Comment by dwtowner** [comment]
I think it now fails for unrelated reasons. At least, I can't see any build or test errors relating to my new code.

**Comment by peastman** [comment]
See https://dev.azure.com/openmm/openmm/_build/results?buildId=319&view=logs&j=b99857f5-7209-5321-71ca-df9144f851a2&t=7738dc48-0fea-5887-4721-6bac7cf9ddad.  There are lots of errors like this:

```
FAILED: platforms/cpu/sharedTarget/CMakeFiles/OpenMMCPU.dir/__/src/CpuNonbondedForceAvx2.cpp.obj 
C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe  /nologo /TP -DOPENMM_BUILD_VERSION=0 -DOPENMM_LIBRARY_NAME=OpenMM -DOPENMM_MAJOR_VERSION=7 -DOPENMM_MINOR_VERSION=5 -DOpenMMCPU_EXPORTS -DWIN32 -ID:\a\1\s\platforms\cpu\src -ID:\a\1\s\platforms\cpu\.\include -ID:\a\1\s\src -ID:\a\1\s\libraries\asmjit -ID:\a\1\s\libraries\pthreads\include -ID:\a\1\s\libraries\vecmath\include -ID:\a\1\s\libraries\irrxml\include -ID:\a\1\s\serialization\include -ID:\a\1\s\platforms\reference\include -ID:\a\1\s\libraries\csha1\include -ID:\a\1\s\libraries\hilbert\include -ID:\a\1\s\libraries\lbfgs\include -ID:\a\1\s\libraries\sfmt\include -ID:\a\1\s\libraries\lepton\include -ID:\a\1\s\libraries\quern\include -ID:\a\1\s\libraries\jama\include -ID:\a\1\s\olla\include -ID:\a\1\s\openmmapi\include -ID:\a\1\s\.\include -ID:\a\1\s\tests /DWIN32 /D_WINDOWS /W2 /GR /EHsc /wd4305 /wd4244 /MD /O2 /Ob2 /DNDEBUG    -DLEPTON_USE_JIT -DOPENMM_CPU_BUILDING_SHARED_LIBRARY  -DLEPTON_USE_JIT /arch:AVX2 /D__AVX2__ /showIncludes /Foplatforms\cpu\sharedTarget\CMakeFiles\OpenMMCPU.dir\__\src\CpuNonbondedForceAvx2.cpp.obj /Fdplatforms\cpu\sharedTarget\CMakeFiles\OpenMMCPU.dir\ /FS -c D:\a\1\s\platforms\cpu\src\CpuNonbondedForceAvx2.cpp
D:\a\1\s\openmmapi\include\openmm/internal/vectorizeAvx2.h(49): error C4235: nonstandard extension used: '__asm' keyword not supported on this architecture
D:\a\1\s\openmmapi\include\openmm/internal/vectorizeAvx2.h(49): error C2059: syntax error: ':'
```

And at https://travis-ci.org/github/openmm/openmm/jobs/694672021:

```
In file included from /home/travis/build/openmm/openmm/tests/TestVectorizeAvx.cpp:37:0:
/home/travis/build/openmm/openmm/openmmapi/include/openmm/internal/vectorizeAvx.h:36:10: fatal error: immintrin.h: No such file or directory
 #include <immintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
```

**Comment by dwtowner** [comment]
I find the CI logs quite confusing. For example, the link you sent to part of the build process has a green tick against it, implying it was successful! Shouldn't the CI be failing that section if the build had errors?

I've fixed the two errors you pointed out and they appear to pass now. The CI build still fails, but apparently because of TestReferenceRpmd, which is marked as stochastic.

**Comment by peastman** [comment]
> Shouldn't the CI be failing that section if the build had errors?

You'd think that, wouldn't you?  But apparently not.  It doesn't indicate an error until the next section, when it tries to run the tests and finds they don't exist.

**Pull request merged**
