### PR TITLE
Prevent Windows from defining macros that interfere with other code

### PR DESCRIPTION
**Pull request by mikemhenry**

### CODE REVIEW

**Comment by peastman** [comment]
It's best to put it at the very top of the file, before the first `#include`.  In order to work, the symbol has to be defined before anything includes the header with the unwanted macros.

**Comment by mikemhenry** [comment]
Looks like the failing test on windows fails occasionally, but I don't have the permissions to re-run it.

**Comment by peastman** [comment]
It's just a stochastic failure.  You can ignore it.

**Comment by peastman** [comment]
Thanks!

**Pull request merged**
