### PR TITLE
Enable docker for GPU builds

### PR DESCRIPTION
**Pull request by swails**
I finally got nvidia-docker2 installed and actually working on my Gentoo
machine (I had to disable their restriction of using GPU devices to
users in the 'video' group, since the nvidia container runtime hook
didn't run as a user with those privileges, and I can't figure out what
user it was running as).

The other GPU-enabled node I added to the Jenkins array runs Ubuntu, and
that one already has nvidia-docker2 installed and running correctly on
it.

### CODE REVIEW

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
@peastman - this is ready to merge whenever.  It only touches files inside the `devtools/ci/jenkins` folder and will result in the GPU tests being run inside a docker container (which will isolate the tests from experiments I do on the Jenkins and slave machines).

**Comment by peastman** [comment]
Thanks!  I'll merge as soon as the tests finish running.

**Comment by peastman** [comment]
The jenkins build for the CPU platform is failing:

```
[ 72%] Linking CXX shared library ../../libOpenMMCudaCompiler.so
/usr/bin/ld: cannot find -lOpenMMCUDA
collect2: error: ld returned 1 exit status
```

I suspect that `OPENMM_BUILD_CUDA_COMPILER_PLUGIN` is incorrectly turned on in that build?

**Comment by swails** [comment]
I'm not sure what the Travis failure is, but it can't be related to this PR (and it passed last time).

Jenkins is passing tests now.

**Comment by peastman** [comment]
Thanks!

**Pull request merged**
