### PR TITLE
Use coarser granularity to split work in PME kernels

### PR DESCRIPTION
**Pull request by mark-mb**
Reduce necessary synchronization between threads, and improve memory locality.

### CODE REVIEW

**Comment by peastman** [comment]
What sort of benchmarks have you tested this on?  My experience is that statically splitting the work leads to worse scaling with number of cores, since you often get just one thread that keeps running long after all the others have finished.

If the atomic counter is actually adding significant overhead, we can reduce that pretty easily without losing the benefit.  Instead of having threads grab one particle at a time, break the particles into `numThreads*10` blocks and have threads grab a block of particles at a time.  That's fine grained enough to give pretty good balancing between threads.  And since on average each thread only accesses the counter 10 times in total, the overhead is completely negligible.  You can see an example of doing that in CpuNonbondedForce:

https://github.com/openmm/openmm/blob/d51ef9e650836517690b9481f12cf3f0e44e24e6/platforms/cpu/src/CpuNonbondedForce.cpp#L438-L444

**Comment by mark-mb** [comment]
> What sort of benchmarks have you tested this on?

I tested it on the benchmarks available in examples/benchmarks.py. I didn't see any slowdown in platforms with very few cores, and I saw a significant improvement in both Intel and Arm for platforms with more cores.

For Intel with 96 cores, I got 15% improvement in pme, 2% (could be noise) in apoa1pme, and 30% in apoa1ljpme

For Arm with 16 cores, I got 35% improvement in pme, 35% in apoa1pme and 50% in apoa1ljpme

> My experience is that statically splitting the work leads to worse scaling with number of cores, since you often get just one thread that keeps running long after all the others have finished.

That depends on the workload. In this particular case, every iteration is very homogeneous in the amount of work, because the number of iterations in the internal loops are fixed.

If the number of iterations to be done for each particle was variable depending, for example, on the input data, then I would agree with you.

> If the atomic counter is actually adding significant overhead, we can reduce that pretty easily without losing the benefit. Instead of having threads grab one particle at a time, break the particles into `numThreads*10` blocks and have threads grab a block of particles at a time. That's fine grained enough to give pretty good balancing between threads. And since on average each thread only accesses the counter 10 times in total, the overhead is completely negligible.

If you are still not convinced that this implementation gives improvements, I'll do that.

**Comment by peastman** [comment]
Give it a try and see.  I suspect it will do at least as well, and perhaps better.

**Comment by mark-mb** [comment]
The results are very similar. There seems to be a slight improvement in some cases. I pushed the new version

**Comment by peastman** [comment]
Looks great.  Thanks!

**Pull request merged**
