### PR TITLE
[macOS Support] Add .DS_Store

### PR DESCRIPTION
**Pull request by philipturner**
Refs: https://github.com/openmm/openmm/issues/3916

Specific files for other operating systems can come later.

### CODE REVIEW

**Comment by peastman** [comment]
Looks good.  OpenMM 8.0 is in release candidate, so we're currently only merging critical bug fixes.  I'll merge this as soon as 8.0 is out.

**Comment by philipturner** [comment]
> only merging critical bug fixes.

I assume that includes setting correct SIMD width on Mac? I'd be disappointed otherwise. Setting correct force threads could wait.

**Comment by peastman** [comment]
Critical bug fixes means things that corrupt data, crash, or produce incorrect results.  Optimizations need to wait for 8.1.  As long as no critical bugs are found, the current release candidate will become the release in about a week.

**Comment by peastman** [comment]
Thanks!

**Pull request merged**
