### PR TITLE
Restraint existing atoms during addHydrogens

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
Second attempt at #2443 with a cleaner git history.

### CODE REVIEW

**Comment by peastman** [comment]
Git does very strange things...

**Comment by peastman** [comment]
Thanks!

**Comment by JoaoRodrigues** [comment]
Forgot to link the original issue: #2432

**Comment by zhang-ivy** [comment]
I can see that this has been merged into master, however it looks like it’s not in the OpenMM 7.4.1  release, as the change isn’t in the 7.4_branch, even though the merge predates the release. @peastman: Do you know if this is intentional or not? If not, could we include this in the next release?

**Comment by jchodera** [comment]
I've queued this for the OpenMM 7.5 project board!

**Pull request merged**
