### PR TITLE
Fixed errors with patches in CHARMM Drude force field

### LINKED ISSUE #3815: CHARMM-Drude 2019 residue patch
Hi OpenMM devs!

I'm currently trying to simulate the amino acid ARG capped with ACE and NME. Following the CHARMM convention, I just included ACE and NME atoms into the ARG single residue. It seems like `modeller.addExtraParticles()` does not work properly since No template found for residue 1 (ARG).

```
from openmm.app import *
from openmm import *
from openmm.unit import *

pdb = PDBFile('./test.pdb')
forcefield = ForceField('charmm_polar_2019.xml')
modeller = Modeller(pdb.topology, pdb.positions)
modeller.addExtraParticles(forcefield)
```

I think the input topology is defined correctly. Is there any problem regarding `modeller.addExtraParticles()` for patch residues? For instance, I've checked that such function correctly added the drude particles for standard residues. There were some issues regarding disulfide patch in CHARMM-Drude 2019 (as seen in #2848) but idk this is also the case. I installed OpenMM 7.7 via source compile and below is the test.pdb file I've used. All bonds (including ARG) are defined.

```
REARGK   1 CREATED WITH OPENMM 7.7, 2022-10-23
CRYST1   39.352   42.600   80.000  90.00  90.00  90.00 P 1           1 
HETATM    1  CH3 ARG A   1      12.588   0.951  34.637  1.00  0.00           C  
HETATM    2  H1  ARG A   1      12.260   0.249  35.404  1.00  0.00           H  
HETATM    3  H2  ARG A   1      13.545   0.625  34.232  1.00  0.00           H  
HETATM    4  H3  ARG A   1      11.848   0.986  33.838  1.00  0.00           H  
HETATM    5  CF  ARG A   1      12.740   2.325  35.246  1.00  0.00           C  
HETATM    6  OF  ARG A   1      12.533   2.493  36.449  1.00  0.00           O  
HETATM    7  N   ARG A   1      13.123   3.308  34.425  1.00  0.00           N  
HETATM    8  H   ARG A   1      13.287   3.070  33.458  1.00  0.00           H  
HETATM    9  CA  ARG A   1      13.320   4.724  34.793  1.00  0.00           C  
HETATM   10  HA  ARG A   1      12.513   5.017  35.464  1.00  0.00           H  
HETATM   11  CB  ARG A   1      14.696   4.870  35.487  1.00  0.00           C  
HETATM   12  HB2 ARG A   1      15.464   5.019  34.729  1.00  0.00           H  
HETATM   13  HB3 ARG A   1      14.948   3.936  35.989  1.00  0.00           H  
HETATM   14  CG  ARG A   1      14.814   5.995  36.536  1.00  0.00           C  
HETATM   15  HG2 ARG A   1      15.799   5.913  36.994  1.00  0.00           H  
HETATM   16  HG3 ARG A   1      14.768   6.962  36.034  1.00  0.00           H  
HETATM   17  CD  ARG A   1      13.761   5.964  37.662  1.00  0.00           C  
HETATM   18  HD2 ARG A   1      12.850   6.442  37.301  1.00  0.00           H  
HETATM   19  HD3 ARG A   1      14.124   6.550  38.506  1.00  0.00           H  
HETATM   20  NE  ARG A   1      13.423   4.587  38.070  1.00  0.00           N  
HETATM   21  HE  ARG A   1      12.989   4.012  37.361  1.00  0.00           H  
HETATM   22  CZ  ARG A   1      13.671   3.938  39.187  1.00  0.00           C  
HETATM   23  NH1 ARG A   1      14.257   4.485  40.215  1.00  0.00           N  
HETATM   24 HH11 ARG A   1      14.531   5.456  40.162  1.00  0.00           H  
HETATM   25 HH12 ARG A   1      14.433   3.947  41.052  1.00  0.00           H  
HETATM   26  NH2 ARG A   1      13.319   2.689  39.256  1.00  0.00           N  
HETATM   27 HH21 ARG A   1      12.899   2.273  38.436  1.00  0.00           H  
HETATM   28 HH22 ARG A   1      13.475   2.139  40.089  1.00  0.00           H  
HETATM   29  C   ARG A   1      13.248   5.598  33.528  1.00  0.00           C  
HETATM   30  O   ARG A   1      13.734   5.174  32.490  1.00  0.00           O  
HETATM   31  NJ  ARG A   1      12.675   6.804  33.549  1.00  0.00           N  
HETATM   32  HJ  ARG A   1      12.710   7.284  32.661  1.00  0.00           H  
HETATM   33  CJ  ARG A   1      11.950   7.456  34.640  1.00  0.00           C  
HETATM   34  HJ1 ARG A   1      12.642   7.785  35.416  1.00  0.00           H  
HETATM   35  HJ2 ARG A   1      11.204   6.784  35.063  1.00  0.00           H  
HETATM   36  HJ3 ARG A   1      11.432   8.334  34.254  1.00  0.00           H  
TER      37      ARG A   1
CONECT    1    2    3    4    5
CONECT    2    1
CONECT    3    1
CONECT    4    1
CONECT    5    1    6    7
CONECT    6    5
CONECT    7    8    9    5
CONECT    8    7
CONECT    9    7   10   11   29
CONECT   10    9
CONECT   11   12   13    9   14
CONECT   12   11
CONECT   13   11
CONECT   14   15   16   11   17
CONECT   15   14
CONECT   16   14
CONECT   17   18   19   14   20
CONECT   18   17
CONECT   19   17
CONECT   20   21   17   22
CONECT   21   20
CONECT   22   20   23   26
CONECT   23   24   25   22
CONECT   24   23
CONECT   25   23
CONECT   26   27   28   22
CONECT   27   26
CONECT   28   26
CONECT   29    9   30   31
CONECT   30   29
CONECT   31   32   33   29
CONECT   32   31
CONECT   33   34   35   36   31
CONECT   34   33
CONECT   35   33
CONECT   36   33
END
```

### PR DESCRIPTION
**Pull request by peastman**
Fixes #3815 and #3828.  @smlee99 and @andrewsb8 can you try it out and see if it fixes your problems?  You can just download the new XML file anywhere on your computer, then give the path to it to the ForceField constructor.

This was created using two ParmEd changes that haven't yet been merged: https://github.com/ParmEd/ParmEd/pull/1275 and https://github.com/ParmEd/ParmEd/pull/1278.

### CODE REVIEW

**Comment by smlee99** [comment]
Looks like new XML file is properly recognizing the ACE-ARG-NME patch residue without any problem. Thanks for your work. Really appreciate it!

**Comment by andrewsb8** [comment]
I see in the new xml file the lines for the hydrogen. I am still getting a particle position = nan error, but the stack trace is different than reported in #3828 

```
Traceback (most recent call last):
  File "/data/B/bandrews/OpenMM/GGG_CHARMM_Drude_2019_SWM4-NDP_water/openmm_setup.py", line 75, in <module>
    simulation.step(600000000)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/simulation.py", line 134, in step
    self._simulate(endStep=self.currentStep+steps)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/simulation.py", line 236, in _simulate
    self._generate_reports(wrapped, True)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/simulation.py", line 258, in _generate_reports
    reporter.report(self, state)
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/dcdreporter.py", line 107, in report
    self._dcd.writeModel(state.getPositions(), periodicBoxVectors=state.getPeriodicBoxVectors())
  File "/home/bandrews/miniconda3/envs/openMM/lib/python3.9/site-packages/openmm/app/dcdfile.py", line 125, in writeModel
    raise ValueError('Particle position is NaN')
ValueError: Particle position is NaN
```
I could look into which particle is producing the NaN value. But that will take some time. Thanks for making the change to the forcefield! I think the stack trace changing is at least encouraging.

Brian

**Comment by peastman** [comment]
Does it become nan within the first few steps, or does it take a while?  If the latter, it probably is something different.  [The FAQ](https://github.com/openmm/openmm/wiki/Frequently-Asked-Questions#nan) has advice on debugging problems of this sort.

**Comment by andrewsb8** [comment]
It has varied between 50K and 250K time steps.

I am finding my system with a negatively charged C terminus also results in a particle coordinate is nan but after 1 million time steps, so I have not realized this system was also breaking with the same stack trace. Reducing time steps or further energy minimization has not resolved this issue so far. I will continue trouble shooting. Thanks again for your help.

**Comment by smlee99** [comment]
Hi? I also had a similar issue while running a single amino acid residue (but not GLY) with negatively charged C residue. From here, this is a bit my guess about this issue. (I did not try it yet) For `charmm_polar_2019.xml` file, `<AllowPatch name="CNEG"/>` and `<AllowPatch name="CTEG"/>` are used for C-termius residue. If you check the original .str file for such force field in [here](http://mackerell.umaryland.edu/charmm_drude_ff.shtml) (file: drude_toppar_2019.str), below is the definition of `CNEG` and `CTEG` residue.
```
PRES CNEG          0.000 ! protonated C-terminus for polypeptide with terminal glycine
                         ! Yes, the patch name is not ideal; the total charge is zero
!
!    OT2-HT
!    /
! --C
!    \\
!    OT1
!
DELETE ATOM O
DELETE ATOM DO
DELETE ATOM LPOA
DELETE ATOM LPOB

PRES CTEG         -1.000 ! C-terminus for polypeptide terminating with a glycine
!
!     OT2(-)
!    /
! --C
!    \\
!     OT1
!
DELETE ATOM O
DELETE ATOM DO
DELETE ATOM LPOA
DELETE ATOM LPOB
```
I don't know the specific detail about force field parameterization but at least it shows that this residue is suitable for polypeptide terminating with a glycine. Well for your single amino acid case, there is another C-terminus residue used for single amino acid.
```
PRES CNES          0.000 ! protonated C-terminus for single amino acid
! Note: with ACE use CNEU
!
!    OT2-HT
!    /
! --C
!    \\
!    OT1
!
DELETE ATOM O
DELETE ATOM DO
DELETE ATOM LPOA
DELETE ATOM LPOB

PRES CTES         -1.000 ! C-terminus for single amino acid
! Note: with ACE use CTER
!
!     OT2(-)
!    /
! --C
!    \\
!     OT1
!
DELETE ATOM O
DELETE ATOM DO
DELETE ATOM LPOA
DELETE ATOM LPOB
```
In current `charmm_polar_2019.xml` file, `forcefield.createsystem` does not automatically check whether C-terminus patch is for single amino acid or polypeptide, and since both [`CTES`,`CNES`] and [`CTEG`,`CNEG`] have same topology information, only one of them is defined in xml file. I'm not sure if it would work or not but you may add parameters for [`CTES`,`CNES`] patch, change the `<AllowPatch>` from [`CTEG`,`CNEG`] to  [`CTES`,`CNES`], and run the simulation for trobleshooting.

**Comment by peastman** [comment]
This is kind of an impedance mismatch between CHARMM and OpenMM.  In CHARMM, patches are a tool for modelling.  The user tells it, "Apply this patch to this residue," and it modifies the residue as specified.  It's up to the user to read the comments and figure out what patch makes sense.  It doesn't specify programmatically that one patch is only intended for single residues and a different one for polypeptides.

In OpenMM, patches are a tool for parametrization.  The force field receives a model that as already been modified in some way, and it has to try to figure out what patch was used to do it so it can pick correct parameters.  For all it knows, you could have applied CTES to a polypeptide or CTEG to a single amino acid.  That isn't how they were intended to be used, but that intent isn't recorded in any machine readable way.

I doubt this would cause the simulation to blow up though.  The two patches are very similar.  As far as the simulation code is concerned, both versions should work equally well.  One may give a more realistic description of how the charge is distributed in a particular real molecule, but the simulation code doesn't care how physically accurate your model is, just whether it's numerically well behaved.

**Comment by andrewsb8** [comment]
@smlee99 Thank you for the suggestion! I am simulating triglycine so the issue between patches for amino acids and polypeptides shouldn't apply here since I am simulating the latter. I also agree with Dr. Eastman that either patch should not cause the system to blow up.

**Pull request merged**
