### PR TITLE
Update installation instructions for the new conda-forge packages

### PR DESCRIPTION
**Pull request by jaimergp**
We need to cover

- [x] Default installation with no versions, and what it will default to
- [x] How to specify a CUDA version
- [x] Leave old instructions for <=7.4 (?)
- [ ] FAQ

### CODE REVIEW

**Comment by peastman** [comment]
> Leave old instructions for <=7.4 (?)

No need.  We just need to say how to install the current version.

> FAQ

What does this refer to?

**Comment by jaimergp** [comment]
> What does this refer to?

Solutions to common problems we might find during testing. Like those `__cuda==xxx` errors caused by misconfigured channels. Hopefully there's nothing to report.

**Comment by peastman** [comment]
Looks good!  Can you also update the command for installing openmm-setup?

**Comment by jaimergp** [comment]
Done!

**Comment by peastman** [comment]
Can you go ahead and mark this as ready to merge?  What you have is fine, and I think this is all that's holding up the release.

**Comment by jaimergp** [comment]
Done!

**Comment by peastman** [comment]
Thanks!

**Pull request merged**
