### PR TITLE
Debug failing CI builds

### PR DESCRIPTION
**Pull request by peastman**

### CODE REVIEW

**Comment by peastman** [comment]
Two of our CI builds spontaneously started failing in December.  I've traced the failure of the docs build to what I think is a bug in Linkinator, which we use to check for broken links.  I've reported the problem to them.  Hopefully they'll release a fix soon.  If not, we can work around it by pinning to an earlier version that didn't have the problem.

I'm less certain about why the Windows build started failing.  It successfully gets through building the Python API and doesn't report any problems.  But when we run the tests, `import openmm` fails with the error

```
 ImportError: DLL load failed while importing _openmm: The specified module could not be found.
```

I verified that the file `_openmm.cp39-win_amd64.pyd` is present in the directory, so most likely this indicates a linker error with some library it depends on.  I ran `dumpbin` on it, which is roughly the Windows equivalent of `ldd`.  Here is the output:

```
Dump of file D:\conda-envs\build\lib\site-packages\openmm\_openmm.cp39-win_amd64.pyd

File Type: DLL

  Image has the following dependencies:

    OpenMM.dll
    OpenMMAmoeba.dll
    OpenMMRPMD.dll
    OpenMMDrude.dll
    python39.dll
    MSVCP140.dll
    KERNEL32.dll
    VCRUNTIME140_1.dll
    VCRUNTIME140.dll
    api-ms-win-crt-stdio-l1-1-0.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll

  Summary

       1D000 .data
        A000 .pdata
      111000 .rdata
        4000 .reloc
        1000 .rsrc
      188000 .text
```

Unfortunately, unlike `ldd` it doesn't give information about where they're being resolved to.  The fact that it spontaneously started failing a month ago suggests it's caused by a change to something else in the environment.  Maybe a change to something in conda-forge created a binary incompatibility?

**Comment by mikemhenry** [comment]
I just noticed that the mac arm builds are failing, looking at the logs the jobs are getting killed, not sure why but I've rebooted the mac mini so we can see if that fixes it

**Comment by swails** [comment]
Is the arm Mac runner self-hosted?

**Comment by jchodera** [comment]
@swails : Yes---it's located with @mikemhenry running a modified GitHub Actions runner since support for `arm-osx` was not available when we set it up. 

Is there a better cloud solution we should be looking into?

**Comment by swails** [comment]
MacStadium is the de facto Mac cloud platform.  We were going to reserve instances with them until Mac support became unnecessary.  That's a $119/month (with 1 yr reservations) expense, though.

Eventually GHA will add M1 runners and self-hosted can be dropped entirely.

I'm over Mac myself and haven't used them for anything since ca. 2016

**Comment by mikemhenry** [comment]
I don't have time to dig into this now, but I'm pretty sure the errors are "real" and I need to crank up the verbosity on ctest, since many tests do pass, so the runner itself is working fine.

**Comment by mikemhenry** [comment]
OSX isn't fun to run headless, this is why it wasn't starting:
https://github.com/actions/runner/issues/349
It should be good now, try and restart it. I also need to make the cleanup step something that always runs, so if it fails in the middle it still will clean itself up

**Comment by peastman** [comment]
The M1 now starts, but it fails in just a few seconds.  The log isn't too informative.

```
2022-02-10T01:22:45.2262900Z Checking for cached Miniforge3-MacOSX-arm64.sh@0.0.0-86ebc55b71b8f61882f2ac12c4e1758bcbaa4ebd0f61c8293e3a442e1dde26a6...
2022-02-10T01:22:45.2284680Z Found Miniforge3-MacOSX-arm64.sh cache at /Users/lilmac/Projects/GH-Runner/actions-runner/_work/_tool/Miniforge3-MacOSX-arm64.sh/0.0.0-86ebc55b71b8f61882f2ac12c4e1758bcbaa4ebd0f61c8293e3a442e1dde26a6/x64!
2022-02-10T01:22:45.2285320Z ##[endgroup]
2022-02-10T01:22:45.2285720Z ##[group]Running installer...
2022-02-10T01:22:45.2290650Z ##[endgroup]
2022-02-10T01:22:45.2332440Z ##[error]Unknown installer extension: 
2022-02-10T01:22:45.2547610Z Post job cleanup.
```

**Comment by jchodera** [comment]
@mikemhenry : This may be relevant: 
https://github.com/hkratz/gha-runner-osx-arm64/pull/2

**Comment by mikemhenry** [comment]
Okay, failing but now in a different way. I think it will be best for me to troubleshoot this as a separate PR so that I can trigger the CI as I troubleshoot. I remember running into this error before, just need to dig through my notes on how I solved it last time.

**Comment by peastman** [comment]
All the builds running on Github are now working, so I'm going to close this.  The M1 Mac build is still failing, but that can be debugged in a separate PR.

**Comment by jchodera** [comment]
> The M1 Mac build is still failing, but that can be debugged in a separate PR.

@peastman : Can you open a separate issue for this and assign @mikemhenry ?

**Pull request closed without merging**
