### PR TITLE
fix Charmm NBThole calculation bug and Improper dihedral parameter match issue

### LINKED ISSUE #2750: CHARMM Drude NBThole implementation
There is a difference in charmm and openmm energies for drude systems. 
```
Software | Version | Energy (kcal/mol)
         |         | FULL      | Only DNA | Only WATER | Only IONS
Charmm   | c44b2   | -99876.39 | -3054.58 |  -84250.37 | -93.45
OpenMM   | 7.4.2   | -98798.26 | -2245.06 |  -83989.81 | -85.04
``` 
The difference appears to be coming from this modification to add exception parameters into NBThole by @jing-huang

[https://github.com/openmm/openmm/commit/31f7f3559990caa924560118dfdf7f8be835d6fe](url)

Energies after commenting this part are acceptable. However there is a difference in water energy and ions which is another issue to solve.
```
Software | Version | Energy (kcal/mol)
         |         | FULL      | Only DNA | Only WATER | Only IONS
Charmm   | c44b2   | -99876.39 | -3054.58 |  -84250.37 | -93.45
OpenMM   | 7.4.2   | -98798.26 | -2245.06 |  -83989.81 | -85.04
OpenMM   | mod     | -99597.54 | -3044.19 |  -83989.92 | -85.04
``` 
Thanks.

### PR DESCRIPTION
**Pull request by qiuzy**
this commit fixes #2750 and #2895 

In the commit, NBThole interaction calculation bug is fixed. 
And improper dihedral match problem is fixed.
More discussion on the two issues can be found in #2944 

And also multiple dihedral with the same periodicity check problem is also fixed.

### CODE REVIEW

**Comment by peastman** [comment]
Thanks!  Can you add a test case that verifies this fixes the problem?  This simplest way is to create a minimal system (just a few atoms) that gives the wrong energy without this fix but the right energy with it.  The files can go in `wrappers/python/tests/systems` and the test method in TestCharmmFiles.py.

**Comment by qiuzy** [comment]
I have added a test system of CYT-GUA-CYT short DNA segnment to test NBThole.

**Comment by peastman** [comment]
Thanks!  Looks good.

**Comment by mdpoleto** [comment]
Are those fixes included in the current conda package (v7.5)? If not, are there any plans on this?

**Comment by peastman** [comment]
7.5 was released on Dec. 9, and this was fixed on Dec. 20.  It will be in the next major release, or if you think it's urgent we could try to include it in a patch release.

**Comment by mdpoleto** [comment]
I believe this is a critical fix for Drude force field users since it directly impacts potential energy and nonbonded calibrations. Currently, v7.5 does not issue any warning on this, so, in my opinion, a patch release is much needed.

**Comment by mdpoleto** [comment]
I see this was added to 7.5.1 milestones and they are all closed now. Thank you @peastman. Should we expect a release as a conda package soon?

**Comment by peastman** [comment]
We're hoping to get a release candidate posted this week or next week.

**Pull request merged**
