### PR TITLE
Fix 2360

### LINKED ISSUE #2360: amber_file_parser produces system with nonzero SA term, even though None is requested
### Expected behavior 

Passing `gbsaModel=None` kwarg to `prmtop.createSystem` should yield a system with a nonzero GB, and a zero SA term.

### Actual behavior

A system is created containing a `GBSAForce` with nonzero SA term.

### Suggested fix

Add a check for `gbsaModel is None` [here](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/amber_file_parser.py#L988-L991), and set surface area energy to 0 if so.

If this sounds good, I'm happy to open a PR and finally become a contributor to OpenMM :-) 

### Reproducing example

[omm_gb_nonzero_sa_inputs.tar.gz](https://github.com/pandegroup/openmm/files/3469577/omm_gb_nonzero_sa_inputs.tar.gz)
```
from simtk import openmm, unit
from simtk.openmm.app import AmberPrmtopFile, AmberInpcrdFile
import copy

prmtop_file = AmberPrmtopFile('AlkEthOH_r19.top')
# AmberInpcrdFile parses also rst7 files.
inpcrd_file = AmberInpcrdFile('AlkEthOH_r19.crd')
# Create system and update box vectors (if needed)
system = prmtop_file.createSystem(implicitSolvent=openmm.app.OBC2,
                                  nonbondedMethod = openmm.app.forcefield.NoCutoff,
                                  nonbondedCutoff=None,
                                  gbsaModel=None,
                                  implicitSolventKappa=0.)

# Store numpy positions.
positions = inpcrd_file.getPositions(asNumpy=True)

gbsa_force = [force for force in system.getForces() if isinstance(force, openmm.GBSAOBCForce)][0]

print(gbsa_force.getSurfaceAreaEnergy())

# Set GBSAForce to ForceGroup 1
gbsa_force.setForceGroup(1)
integrator = openmm.VerletIntegrator(1.0 * unit.femtoseconds)
context = openmm.Context(system, copy.deepcopy(integrator))

# Get context energies
context.setPositions(positions)

# Determine how many force groups we need to compute.
force_groups = {f.getForceGroup() for f in context.getSystem().getForces()}

# Compute potential energies of all groups.
potential_energies = {}
for force_group in force_groups:
    state = context.getState(getEnergy=True, groups={force_group})
    potential_energies[force_group] = state.getPotentialEnergy()
print(potential_energies)
```
> 2.25936 kJ/(nm**2 mol)
> {0: Quantity(value=55.730167388916016, unit=kilojoule/mole), 1: Quantity(value=-25.586986541748047, unit=kilojoule/mole)}

```
gbsa_force.setSurfaceAreaEnergy(0)
context = openmm.Context(system, copy.deepcopy(integrator))

# Get context energies
context.setPositions(positions)

potential_energies = {}
for force_group in force_groups:
    state = context.getState(getEnergy=True, groups={force_group})
    potential_energies[force_group] = state.getPotentialEnergy()
print(potential_energies)
```
> {0: Quantity(value=55.730167388916016, unit=kilojoule/mole), 1: Quantity(value=-33.25577926635742, unit=kilojoule/mole)}

### Environment
```
(off-dev) jwagner@MBP-S$ conda list
# packages in environment at /Users/jwagner/miniconda3/envs/off-dev:
#
# Name                    Version                   Build  Channel
ambermini                 16.16.0                       7    omnia
appnope                   0.1.0                 py37_1000    conda-forge
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.1.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
boost                     1.70.0           py37haf112f3_1    conda-forge
boost-cpp                 1.70.0               h75728bb_2    conda-forge
bson                      0.5.8                      py_0    conda-forge
bzip2                     1.0.8                h01d97ff_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.16.0            he1c11cd_1002    conda-forge
certifi                   2019.6.16                py37_1    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             h6de7cb9_1003    conda-forge
fftw3f                    3.3.4                         2    omnia
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.0               h24853df_0    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
glib                      2.58.3            h9d45998_1002    conda-forge
icu                       64.2                 h6de7cb9_0    conda-forge
importlib_metadata        0.18                     py37_0    conda-forge
ipykernel                 5.1.1            py37h5ca1d4c_0    conda-forge
ipython                   7.6.1            py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.0                      py_0    conda-forge
jedi                      0.14.1                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcxx                    8.0.0                         4    conda-forge
libcxxabi                 8.0.0                         4    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgcc                    4.8.5                         1    conda-forge
libgfortran               4.0.0                         0    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0               10_openblas    conda-forge
libopenblas               0.3.6                h4bb4525_5    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libtiff                   4.0.10            hd08fb8f_1003    conda-forge
libxml2                   2.9.9                h12c6b28_2    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
markupsafe                1.1.1            py37h1de35cc_0    conda-forge
mistune                   0.8.4           py37h1de35cc_1000    conda-forge
more-itertools            7.2.0                    pypi_0    pypi
msgpack-python            0.6.1            py37h04f5b5a_0    conda-forge
nbconvert                 5.5.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.3                        py_0    conda-forge
notebook                  6.0.0                    py37_0    conda-forge
numpy                     1.16.4           py37h6b0580a_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.6                h4bb4525_5    conda-forge
openeye-toolkits          2019.4.2                 py37_0    openeye
openforcefield            0.4.1+9.gb01a28b.dirty           dev_0    <develop>
openmm                    7.3.1           py37_cuda92_rc_2    omnia
openssl                   1.1.1c               h01d97ff_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.25.0           py37h86efe34_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parmed                    3.2.0                    py37_0    omnia
parso                     0.5.1                      py_0    conda-forge
pcre                      8.41              h0a44026_1003    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    5.4.1           py37hbddbef0_1000    conda-forge
pip                       19.2.1                   py37_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pycairo                   1.18.1           py37h650f75e_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyparsing                 2.4.1.1                    py_0    conda-forge
pyqt                      5.9.2            py37h2a560b1_0    conda-forge
pyrsistent                0.15.3           py37h01d97ff_0    conda-forge
pytest                    5.0.1                    pypi_0    pypi
python                    3.7.3                h93065d6_1    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1.1            py37h01d97ff_0    conda-forge
pyzmq                     18.0.2           py37hee98d25_2    conda-forge
qt                        5.9.7                h8cf7e54_3    conda-forge
qtconsole                 4.5.2                      py_0    conda-forge
rdkit                     2019.03.2        py37hbdb07b7_1    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sip                       4.19.8          py37h0a44026_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
smirnoff99frosst          1.1.0                         0    omnia
sqlite                    3.29.0               hb7d70f7_0    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             h2573ce8_1002    conda-forge
toml                      0.10.0                     py_0    conda-forge
tornado                   6.0.3            py37h01d97ff_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
widgetsnbextension        3.5.0                    py37_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zipp                      0.5.2                    pypi_0    pypi
zlib                      1.2.11            h01d97ff_1005    conda-forge
zstd                      1.4.0                ha9f0a20_0    conda-forge
```

### PR DESCRIPTION
**Pull request by j-wags**
Fixes #2360 and adds a test for the desired behavior.

@peastman, the test seems much smaller in scope than the others in the file, but I didn't see anywhere else to put it. Let me know if it would fit better elsewhere.

### CODE REVIEW

**Comment by peastman** [comment]
Looks good!  Anyone have any idea why none of the CI builds are starting for this PR?

**Comment by peastman** [comment]
runjenkins

**Comment by peastman** [comment]
Actually I think I know.  It's because we just moved to the openmm organization.  Let's see if I can figure out how to fix that.

**Comment by peastman** [comment]
I've got travis working for new PRs, but I'm not sure how to make it run for this one.  I'll go ahead and merge this and just trust your test is passing.  If it isn't, we'll find out soon enough!

@swails what do we need to do to get jenkins working again?  It looks to me like the webhook is still fine, so it's probably a change needed on your end.  We just transferred the organization, so the request will now come from openmm/openmm instead of pandegroup/openmm.  That broke all the different CI systems.

**Comment by swails** [comment]
Jenkins should be fixed now. Just use "run jenkins" to trigger a build.

**Comment by peastman** [comment]
Thanks!  That just leaves AppVeyor for me to try to figure out.

**Pull request merged**
