### PR TITLE
Update cl.hpp

### PR DESCRIPTION
**Pull request by jaimergp**
Update `cl.hpp` with new version from https://github.com/KhronosGroup/OpenCL-CLHPP/commit/c5063c34675155fffc20185e74ba82a9dfd5dc84

This tries to address https://github.com/openmm/openmm/issues/2499

### CODE REVIEW

**Comment by jaimergp** [comment]
This change doesn't fix the problems we were seeing with the large differences in forces. Refer to https://github.com/conda-forge/openmm-feedstock/pull/16#issuecomment-574121825.

**Comment by peastman** [comment]
We weren't expecting it to fix that.  This only affects the OpenCL platform, but that's a difference between the Reference and CPU platforms.  This does fix the errors about Intel intrinsics?

**Comment by jaimergp** [comment]
Apparently. The build log doesn't contain any more references to `DNO_WARN_X86_INTRINSICS` after I removed that flag in the `conda-forge` PR.

**Comment by peastman** [comment]
Good enough then.  Thanks!

**Pull request merged**
