### PR TITLE
Report status during minimization

### PR DESCRIPTION
**Pull request by peastman**
Implements #1155.

This adds a virtual MinimizationReporter class.  You subclass it, implementing the `report()` method, and pass it to `minimize()`.  It gets called after each iteration.

The Python API was a little challenging.  This is the first time we've had an interface in which C++ code invokes Python code, instead of the other way around.  I ran into some SWIG issues (https://github.com/swig/swig/issues/2670 and https://github.com/swig/swig/issues/2671), but I think I have workarounds for them.

### CODE REVIEW

**Comment by peastman** [comment]
@swails I believe the jenkins failure is because it's using a very old version of SWIG.  Can we upgrade it?

**Comment by sef43** [comment]
One problem I have found when testing this out is that if I use the Python API and have a syntax error in the report method it will not be caught and the minimizer will just silently stop. This could be very problematic for users having to blindly debug their python report code. E.g. this code results in the minimizer stopping with no errors reported.
```python
class Reporter(MinimizationReporter):
    def report(self, iteration, x, grad, args):
        # purposely incorrect python code with a syntax error
        # prnt instead of print
        prnt(iteration)

reporter = Reporter()


# Perform local energy minimization
print("Minimizing energy...")
simulation.minimizeEnergy(reporter=reporter)
```

**Comment by bdenhollander** [comment]
> It's a bigger problem for C++. GCC has a "feature" that it happily lets you omit the return statement from a function that declares a return value, and then it just returns whatever garbage happens to be on the stack. In practice, though, most reporters are likely to be written in Python rather than C++.

Enabling `-Werror=return-type` should catch a [missing return statement](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=43943).

**Comment by peastman** [comment]
I switched to the other design.  Overall I think it will cause fewer problems for users.  Exceptions thrown inside the reporter get propagated back to the caller as expected.  If a reporter implemented in Python omits a return value, SWIG produces the exception

```
TypeError: SWIG director type mismatch in output value of type 'bool'
```

Hopefully that's clear enough.

**Comment by sef43** [comment]
Yes this is much better. Can we explicitly mention this error in the Docs for minimizationReporter? I am not sure if it is common for a user to come across a SWIG error using the Python API in other parts of OpenMM so it might not be very obvious what the problem is.

**Comment by peastman** [comment]
I'm not sure if there's any clean way of doing that.  The API docs are written for the C++ API.  Then they automatically get copied over to the Python API.  We don't have any good mechanism for customizing them at the Python level.

**Pull request merged**
