### PR TITLE
[WIP] Added test script for packaging

### PR DESCRIPTION
**Pull request by jchodera**
Just beginning to add some automation for testing packaging.  Not ready to merge yet.

### CODE REVIEW

**Comment by peastman** [comment]
What's the status of this PR?  Has it been abandoned, or do you still plan to come back to it?

**Comment by jchodera** [comment]
I'm happy to pick it up again if you think it would be useful to automate testing of the binary package.  If not, we can drop it.

**Comment by peastman** [comment]
I'm not entirely clear on what the intended feature is.  When would this script be run, and on what computer?  Will there be similar tests for other OSes?

**Comment by jchodera** [comment]
The original idea was that this would be run by the Jenkins build system immediately after building the binary package, so that we didn't have to have you open it up and test it manually.

**Comment by peastman** [comment]
If you want to have it do that, I have no objection.  It won't eliminate the need for manual testing, though.  There are a lot of situations where a binary works on the machine it was built on, but fails on other machines (especially if they have a different OS version).

So it's up to you whether you want to finish this or just close it.

**Comment by swails** [comment]
I'm not sure why this branch triggered a build.  But the machine it's running on crashed.

**Comment by peastman** [comment]
Closing abandoned PRs.

**Pull request closed without merging**
