### PR TITLE
Additional test case

### PR DESCRIPTION
**Pull request by egallicc**
We investigated random crashes of ATMForce() with a NonbondedForce and the default softplus alchemical potential during replica exchange binding free energy calculations with [AToM-OpenMM](https://github.com/Gallicchio-Lab/AToM-OpenMM). We found that many of these crashes occur at the physical endpoints where Lambda1=Lambda2=0. In these cases, when Direction=1, the ATM potential is u0 and does not depend on u1 (and vice versa for Direction=-1). As a result, u1 is unbound and can overflow when, for example, atoms clash.

This PR excludes from hybridForce() the forces from u1 (or u0) when the corresponding potential is not included in the energy function, avoiding "0*NaN = NaN" occurrences. Similarly, the u1 and u0 energies are checked for NaN values and normalized to a large value.

The PR also includes a new test of ATMForce() with a NonbondedForce() using two approaches, one that triggers atom reordering and the other that does not. It checks that the two approaches return the same perturbation energy.

 Comments/suggestions are welcome.

### CODE REVIEW

**Comment by peastman** [comment]
I think the changes to the kernel aren't necessary.  The forces are represented in fixed point, not floating point.  Nans aren't an issue.

How did you pick 1e12 as the value to set the force to when it's nan?  That seems rather arbitrary.  Is it specific to the default energy expression, or can we be certain it will always be appropriate for all expressions?

**Comment by egallicc** [comment]
Good point. I guess an overflow in the forces would be reflected in ways other than NaN's.  Would the overflow cause a sign change? Or something else? Empirically, this approach has eliminated all crashes at the endpoints during hundreds of ns of testing.

Right, I was not sure about the cutoff in general. With the default potential and near the endpoint in question, dEdu1 or dEdu0 (depending on the direction) are equal to Lambda2. At the endpoint, Lambda2 should be exactly zero. Because Lambda2 varies in reasonable increments near zero (0.0, 0.1, 0.2, ...), any small cutoff value, maybe including zero, would work fine. But I am not sure in general.

**Comment by egallicc** [comment]
Sorry, you were asking about the maxEnergy value. The default expression includes a softCoreExpression tapering function that brings large perturbation energies down to a set value (Umax). Any large energy value then yields Umax regardless of the specific value. But, yes, it is not clear how to pick the maxEnergy value in general.

What we know is that crashes were not caused by state0Energy or state1Energy overflowing. The crashes were due to numerical instabilities of the forces of the "unused" energy component (u1 or u0) at the endpoint.

**Comment by peastman** [comment]
The maximum possible force that can be represented is about +/- 2e9 kJ/mol/nm.  Your change only omits it when the scale factor <1e-12.  That means the contribution being added to the force will be no more than 2e-3 kJ/mol/nm, orders of magnitude smaller than typical forces.  That shouldn't make any difference.

**Comment by egallicc** [comment]
Could there be some internal conversion to floats during the calculation? And that results in NaNs?

What happens to a long that overflows? Does it stay at the maximum representable value?

**Comment by egallicc** [comment]
We will run more tests following your suggestions to understand the problem better. It will take a while though. The crashes are annoying but rare.

**Comment by egallicc** [comment]
It looks like the crashes in our tests were confounded by mistakenly using two different versions. With 8.1.0 we observed crashes when using PBC's with atom reordering in the main Context. With 8.1.1, no crashes were observed under all tested conditions. (Possibly because of the #4351 fix?). 

Anyway, It is all good. False alarm. I undid the changes in the hybridForce() kernel. 

I left the new NonbondedForce test in `TestATMForce.h` in this PR. It stress-tests ATMForce() by handling a NonbondedForce in two different ways. It can be useful when working on #4395. Let me know if this is acceptable. Otherwise, I will close it.

**Comment by peastman** [comment]
Glad to know it's already fixed.  The new test is fine.  I'll merge it once the builds finish.

**Pull request merged**
