### PR TITLE
Do not add constraints involving extra particles

### LINKED ISSUE #3499: TIP4P waters not compatible with AllBonds?
Hi All,

I'm attempting to run a system with TIP4Pew waters using the "AllBond" constraint option, but I get the following error:
```
openmm.OpenMMException: A constraint cannot involve a massless particle
```
I'm assuming this is because of the virtual site on the water molecules.

Here is the script I'm using:
```
import simtk.openmm.app as app
import simtk.openmm as mm
import simtk.unit as unit
from sys import stdout

import numpy as np

prmtop = app.AmberPrmtopFile('tryp_ben.prmtop')
inpcrd = app.AmberInpcrdFile('tryp_ben.inpcrd')
system = prmtop.createSystem(nonbondedMethod=app.PME, nonbondedCutoff=1*unit.nanometer,
        constraints=app.AllBonds)

num_steps = 10000
time_step = 0.002

input_file = "tryp_ben_new.pdb"

mypdb = app.PDBFile(input_file)

integrator = mm.LangevinIntegrator(298.15*unit.kelvin, 1/unit.picosecond, time_step*unit.picoseconds)
platform = mm.Platform.getPlatformByName('CUDA')
properties = {'CudaDeviceIndex': '0', 'CudaPrecision': 'mixed'}
simulation = app.Simulation(prmtop.topology, system, integrator, platform, properties)
simulation.context.setPositions(mypdb.positions)
simulation.context.setPeriodicBoxVectors(*inpcrd.boxVectors)
simulation.minimizeEnergy()
simulation.context.setVelocitiesToTemperature(298.15 * unit.kelvin)
```

I've attached the files one can use to recreate this error.
[tryp_ben.prmtop.zip](https://github.com/openmm/openmm/files/8181237/tryp_ben.prmtop.zip)
[tryp_ben.inpcrd.zip](https://github.com/openmm/openmm/files/8181238/tryp_ben.inpcrd.zip)

### PR DESCRIPTION
**Pull request by peastman**
Fixes #3499.

### CODE REVIEW

**Comment by swails** [comment]
Test case? It'll be important if we ever replace the implementation with the one from ParmEd (that adds support for other types of systems).

**Comment by peastman** [comment]
Would you be able to make a prmtop and inpcrd containing just a few TIP4P waters?  My skill with AmberTools is minimal.  The files provided in #3499 are quite large.

**Comment by lvotapka** [comment]
Hey @peastman, sorry for the delayed response, I was on vacation last week. If you still need a prmtop/incprd file pair that contains TIP4P, here's some that are pretty small:

[tryp_ben.inpcrd.zip](https://github.com/openmm/openmm/files/8245613/tryp_ben.inpcrd.zip)
[tryp_ben.prmtop.zip](https://github.com/openmm/openmm/files/8245614/tryp_ben.prmtop.zip)

**Comment by peastman** [comment]
Can you make one that's just a few water molecules?  Your prmtop file is 4.8 MB.  We want each test case to run in seconds or less.

**Comment by lvotapka** [comment]
Actually, I just used a smaller peptide and now the prmtop is much smaller.
[small.prmtop.zip](https://github.com/openmm/openmm/files/8248268/small.prmtop.zip)
[small.inpcrd.zip](https://github.com/openmm/openmm/files/8248269/small.inpcrd.zip)

**Comment by peastman** [comment]
That should work great, thanks.

**Comment by peastman** [comment]
Test case added.

**Comment by peastman** [comment]
Tests are passing, so I'll merge it.

**Pull request merged**
