### PR TITLE
Fixes _addIons behavior for membrane systems.

### PR DESCRIPTION
**Pull request by JoaoRodrigues**
Addresses #2439 and problem raised in #2430. 

I'd rather have someone thoroughly review the changes... It took me quite a few hours to figure this out and I'm not sure I got all the behaviour right (especially the test code). Shoutout to @joaomcteixeira for helping debug this.

Thanks for all the patience!

### CODE REVIEW

**Comment by JoaoRodrigues** [comment]
Appveyor build+tests take a very long time - build failed because it reached the 60min limit.

**Comment by peastman** [comment]
I think this fix is way more complicated than it needs to be!  When calling `_addIons()`, why not just scale the ionic strength by the ratio of total waters to replaceable waters?

**Comment by JoaoRodrigues** [comment]
@peastman so you suggest changing the `ionicStrength` value before passing it to `_addIons`?

Note that there are two changes here: one is the indentation of a whole block of code inside `_addIons` (that was adding an additional chain to the topology even when no ions were added) and another is the `numWaters` fix to correct for the number of waters.

**Comment by peastman** [comment]
> @peastman so you suggest changing the ionicStrength value before passing it to _addIons?

Exactly.  Does that sound reasonable?

**Comment by JoaoRodrigues** [comment]
Very. I was just so down the rabbit hole yesterday that this was the simplest I could think of!

**Comment by JoaoRodrigues** [comment]
@peastman, I implemented what you suggested (`ionicStrength  = (numTotalWaters / numReplaceableWaters) * ionicStrength`) but I run into what I think is a rounding/floating point problem (see below). Any suggestions?

```
numTotalWaters = 15884
numReplaceableWaters = 8758  # after filtering for lipid proximity
ionicStrength = (numTotalWaters / numReplaceableWaters) * ionicStrength
# ionicStrength changes from 1M to 1.8136560858643527M

#numIons = 286.38742669930247
# vs. using the total number of waters directly in the numIons formula
# numIons = 286.5342960288809
#
# Test Result 
>       self.assertEqual(resCount['NA'], expected_sodium)
E       AssertionError: 286 != 287
```

**Comment by peastman** [comment]
Is the system charged?  Here's the actual code that calculates the number of ions to add:

```python
numIons = (numReplaceableMols - numPositive - numNegative) * ionicStrength / (55.4 * molar)
```

So really the value we want to use for `ionicStrength` is `(totalWaters-abs(charge)) / (replaceableWaters-abs(charge))`.  So maybe we should add an argument to `_addIons()` with the total number of waters and let it scale the ionic strength itself.

**Comment by JoaoRodrigues** [comment]
> So maybe we should add an argument to _addIons() with the total number of waters and let it scale the ionic strength itself.

That's what I did at first :)

**Comment by peastman** [comment]
This is the only thing holding up 7.4.1.  Can we get it finished up fairly soon?

**Comment by JoaoRodrigues** [comment]
I was about to write you. What is your suggestion then about the code? I can clean up the commits so it's more clear what I changed.

**Comment by peastman** [comment]
How about what I described in https://github.com/openmm/openmm/pull/2440#issuecomment-545982792.  Would that work?

**Comment by JoaoRodrigues** [comment]
That's what I did :) See [here](https://github.com/openmm/openmm/pull/2440/files#diff-79aa2f2e44418fd8c23efbab342f57b5R261)

**Comment by peastman** [comment]
Sorry, I must have misunderstood your comment above!  I thought you were saying there was an error in the current version, and since you hadn't made any more commits since then, I was just waiting.

**Comment by JoaoRodrigues** [comment]
No problem. My editor chomped a ton of white space from the files, so diffing is a mess and makes it much harder to see what I changed. In short, this is what I did:

- Added an argument to `_addIons` that specifies to _total_ number of water molecules in the system. I then use this value in the `numIons` formula to calculate the number of ions to add.
- Put all the ion adding code inside an `if numIons > 0` (or so) statement to avoid adding new (empty) chains to the topology when there aren't ions to be added. This avoid further problems down the road in `addMembrane`.
- adapted `TestModeller.py` to check for the number of ions properly.

**Comment by JoaoRodrigues** [comment]
Thanks!

**Comment by joaomcteixeira** [comment]
:clap:

**Pull request merged**
