### PR TITLE
Add Hosted Environment Instructions. 

### PR DESCRIPTION
**Pull request by mikemhenry**
Supersedes #3607 (That one never got merged in and I didn't want to deal with the merge conflict later, it just adds instructions on how to do dev builds on conda-forge)

I don't have access to the openmm org on andaconda.org, so I used my personal account to test this. To install the env, run `mamba env create mmh/openmm-8-beta`

Let me know if you have any issues. It will probably fail on OSX since we don't have `NNPOps` packages on OSX yet. If that is an issue, we can name spaces these envs, something like `openmm-8-beta-linux` and `openmm-8-beta-osx` etc.

### CODE REVIEW

**Comment by mikemhenry** [comment]
On my linux desktop, this seems to pull in the correct packages:
```
  + openmm              8.0.0beta  py310h2996cf7_1           conda-forge/label/openmm_rc/linux-64           Cached
  + openmm-ml               0.0.1  pyh79ba5db_0              conda-forge/label/openmm_rc/noarch             Cached
  + openmm-torch          1.0beta  cuda112py310h8f78eff_0    conda-forge/label/openmm-torch_rc/linux-64     Cached
```

**Comment by peastman** [comment]
This looks great!  As you predicted, it fails on Mac.  Can you make separate `openmm-8-beta-linux` and `openmm-8-beta-mac` environments?  (It hasn't been called OS X in some years.)

**Comment by mikemhenry** [comment]
@peastman can you double check that `mamba env create mmh/openmm-8-beta-mac` works? I haven't had a chance to test it yet (in the middle of getting the m1 mac mini working :smile: )

**Comment by peastman** [comment]
Still no good:

```
$ mamba env create --file openmm-8-beta-mac.yaml
conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache
pkgs/main/osx-arm64                                         Using cache
pkgs/main/noarch                                            Using cache
pkgs/r/osx-arm64                                            Using cache
pkgs/r/noarch                                               Using cache
conda-forge/label/openmm-torch_rc/noarch                      No change
conda-forge/label/openmm_rc/osx-arm64                         No change
conda-forge/label/openmm_rc/noarch                            No change
conda-forge/label/openmm-torch_rc/osx-arm64                   No change


Looking for: ['openmm==8.0.0beta', 'openmm-ml', 'openmm-torch']


Encountered problems while solving:
  - nothing provides nnpops needed by openmm-ml-0.0.1-pyh79ba5db_0
```

The problem is that the OpenMM-ML package lists NNPOps as a dependency.

**Comment by mikemhenry** [comment]
@peastman thanks for testing!

> The problem is that the OpenMM-ML package lists NNPOps as a dependency.

Is this a necessary dependency? I can make a new build of `OpenMM-ML` where `NNPOps` is only a dependency on Linux, so then it should work on macos.

**Comment by peastman** [comment]
I think that should work.

**Comment by peastman** [comment]
We also should probably update the environment files to specify exact versions of the dependencies, to make sure people test the ones we intend.

**Comment by mikemhenry** [comment]
> We also should probably update the environment files to specify exact versions of the dependencies, to make sure people test the ones we intend.

This is a good idea, once the dust settles around some of the repacking bits we talked about in https://github.com/openmm/openmm/issues/3610#issuecomment-1256551223

**Pull request merged**
