### PR TITLE
Fixed incorrect indexing in kernel

### PR DESCRIPTION
**Pull request by peastman**
This should fix the illegal address error on Jenkins.  It happened on older GPUs.

### CODE REVIEW

**Comment by peastman** [comment]
run jenkins

**Comment by peastman** [comment]
run jenkins

**Comment by peastman** [comment]
@swails We have no jenkins. :(

**Comment by swails** [comment]
Can you check the commit hooks on this repository to make sure it's triggering Jenkins?

**Comment by peastman** [comment]
It's sending requests, but they're failing.  Here's the response from the most recent one.

```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 No valid crumb was included in the request</title>
</head>
<body><h2>HTTP ERROR 403 No valid crumb was included in the request</h2>
<table>
<tr><th>URI:</th><td>/ghprbhook/</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>No valid crumb was included in the request</td></tr>
<tr><th>SERVLET:</th><td>Stapler</td></tr>
</table>
<hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.25.v20191220</a><hr/>

</body>
</html>
```

**Comment by peastman** [comment]
This looks relevant: https://github.com/spinnaker/spinnaker/issues/2067

**Comment by swails** [comment]
It seems that `run jenkins` only worked for the (now-deprecated) GitHub Pull Request Builder.  Now that I'm using the "main" GitHub plugin, triggering Jenkins will need to be done from Jenkins itself.

In order to do that, you'll need an account on Jenkins.  My Jenkins instance routes to gitlab.ambermd.org as the authentication provider, so I created you an account there (with no explicit access there).

I will grant that user additional access/running privileges for the purpose of triggering runs and such.  Watch out for an email to your Stanford email address.

**Comment by swails** [comment]
Note that "triggering jenkins" will mean "in addition to the automatic trigger following PR creation, branching off the main repo, and updating a PR" -- those activities should still automatically trigger the build.

**Comment by peastman** [comment]
> those activities should still automatically trigger the build.

Currently they don't.  They get the error message above.

**Comment by swails** [comment]
I checked the "proxy compatibility mode" in the Jenkins setup.  Hopefully that'll fix it.  If not, I may have to tweak my nginx reverse proxy settings, although I haven't touched those in quite awhile.

Can you show me what hooks are enabled in OpenMM (screenshot would work)?

**Comment by peastman** [comment]
The selected options are issue comments, issues, pull requests, pull request review comments, and pushes.

**Comment by swails** [comment]
How many hooks are enabled that point to Jenkins, and what are the URLs they post to?

**Comment by swails** [comment]
If there's a hook that posts to `ghprb`-something, that hook should be deleted.  That URI supported the GitHub Pull Request Builder, which has been deprecated awhile ago.  I switched to a different GitHub plugin with a different URI.  The webhook should point to https://jenkins.jasonswails.com/github-webhook/ now.

**Comment by peastman** [comment]
The only one that's enabled points to https://jenkins.jasonswails.com/ghprbhook/.  There's also one for cloudapp.net, but it's disabled.

**Comment by peastman** [comment]
Ok, I'll try changing.  Thanks!

**Comment by swails** [comment]
Delete that one.  I deleted that plugin and all requests there will fail.

Are there any disabled ones that point to https://jenkins.jasonswails.com/github-webhook/ ?

**Comment by peastman** [comment]
No, there were just those two.  I just changed the URL on the enabled one.

**Comment by swails** [comment]
Make sure it is at least sending the following events:

* Commit comments
* Branch or tag creation
* Issue comments
* Pull requests
* Pull request reviews
* Pull request review comments
* Pushes

The secret will also have to be edited.  I'll let you know when I email you what it should read.

**Comment by peastman** [comment]
Done, thanks.  If I want to manually trigger a build, what's the new way of doing it?

**Comment by swails** [comment]
Go to https://jenkins.jasonswails.com/job/openmm/job/openmm/ and then go to the job you want to trigger (most likely in the Pull Requests tab).

Open the job you want to build then click "Build Now" on the left-hand side.  You'll need to be logged in to do that.  In the upper-right of any page, click the "Log In" button.

**Comment by swails** [comment]
I can't find the secret that's supposed to be used.  I may have to click the "re-register all hooks", which will use the token you sent me to automatically register a new hook on OpenMM (in which case you can delete the old one).

**Pull request merged**
