### PR TITLE
add docs for conda forge releases

### PR DESCRIPTION
**Pull request by jaimergp**
Addresses https://github.com/openmm/openmm/issues/2993#issuecomment-813472836

### CODE REVIEW

**Comment by peastman** [comment]
Thanks!  I'm making my way through the instructions, trying to build 7.5.1rc2.  I'll post any problems or confusing instructions I run into.

Here are the first two issues I've found.

> Make sure source.url is correct.

There is no `url` property in the `source` block.  Do you mean `git_url`?

> Update source.sha256 with the output of openssl sha256 downloaded_file_from_source_url.tar.gz

There's no `sha256` property either.

**Comment by jaimergp** [comment]
Oh, right, I forgot we are using the full git repo instead of a tarball snapshot. I'll update the docs.

**Comment by peastman** [comment]
The PR is at https://github.com/conda-forge/openmm-feedstock/pull/52.  Let me know if it looks ok!

**Comment by jaimergp** [comment]
Looks ok! We need to fix a couple of unrelated issues that popped up there, but looks like the checklist is working!

**Comment by peastman** [comment]
Ok, I'll merge this then.  Thanks!

**Comment by peastman** [comment]
> Once merged, check the CI status on the rc branch.

I'm not sure what this instruction means.  Where do I go to check the CI status of a branch?

**Comment by jaimergp** [comment]
In the feedstock, switch to the rc branch:

image


Then, click on the status icon for the last commit (it should be green):

image

**Comment by peastman** [comment]
Thanks!  The status is green, so I think that means we have a release candidate.  I'll post the announcement.

**Pull request merged**
