### PR TITLE
Common compute framework to unify CUDA and OpenCL code

### PR DESCRIPTION
**Pull request by peastman**
This is the beginning of an implementation of #2471.  So far I've only implemented one class with the common API, CMMotionRemover, but that should give a sense of how this will work.  Instead of having separate OpenCLRemoveCMMotionKernel and CudaRemoveCMMotionKernel classes, there's a single CommonRemoveCMMotionKernel class used by both platforms.  Just based on whether a CudaContext or OpenCLContext gets passed to its constructor, it gets implemented with the correct one.

I'm trying to follow these principles:

1. Use of this framework should always be optional.  If you want to write separate OpenCL and CUDA implementations of a class, that's fine.
2. It should preserve source compatibility with existing plugins.
3. The common API doesn't need to expose every last feature of the OpenCL and CUDA platforms.  I want to keep it relatively simple while still allowing about 90% of forces and integrators to be implemented with it.

By the way, I've learned a lot about C++ while implementing this.  I knew in an abstract sense that templates could get really complicated, but I never before dreamed of writing a method with the signature

```c++
template <class T>
typename std::enable_if<std::is_fundamental<T>::value, void>::type addArg(T& value)
```

### CODE REVIEW

**Comment by peastman** [comment]
My latest commit finally passed a milestone: this PR now deletes more lines of code than it adds.  Lots more to still to do!

**Comment by peastman** [comment]
Some of the travis builds are failing, because it's using an archaic version of gcc (4.8.4) that doesn't have full C++11 support.  I could fix that in a few ways: by telling it to install a newer version, by switching to a newer build environment (the next oldest, Xenial, has gcc 5.4, which includes full C++11 support), or by switching to clang (Trusty has clang 3.5, which also has full C++11 support).  See https://docs.travis-ci.com/user/languages/cpp/.

Any preference between these?

**Comment by andysim** [comment]
I'm painfully aware of the incompleteness of GCC 4.8, given that we're running CentOS 7 on many of our systems and that's the default compiler.  When compiling with Intel's icpc, the underlying GCC is still used on the backend so brace yourself for a number of error reports including the message `error: namespace "std" has no member "is_trivially_copyable"`.  Thankfully the fix is simple, the user just needs to add `-gxx-name=/path/to/a/non/ancient/gcc/compiler/bin/g++` to the `CXXFLAGS`, as well as prepending `/path/to/a/non/ancient/gcc/compiler/lib64` to `LD_LIBRARY_PATH` before running.

In terms of Travis, I don't have any strong opinion but I think that GCC compatibility is important to guarantee, even though clang is faster and produces faster code.  When we used Travis for Psi4, we often found timeouts when installing dependencies via conda / apt-get, so if it's possible to spin up an environment with a compatible GCC baked in, that's probably the way to go.

**Comment by andysim** [comment]
I simplified the test [patch is here](https://github.com/openmm/openmm/files/4010246/patch.txt) and it looks like the center of mass motion is indeed nonzero on Cuda, but zero on Reference.

**Comment by peastman** [comment]
You're completely right—it was a problem in CMMotionRemover.  Thanks!  It would have taken me a very long time to track that down.

For travis, I think it will be simplest to just update the build environment to xenial.  That has a gcc version that's still pretty old, but new enough to support the full C++11 spec.

**Comment by jchodera** [comment]
I know OpenMM isn't a Python-only project, but we've been trying to standardize the computational molecular sciences community about the [MolSSI Cookiecutter](https://github.com/MolSSI/cookiecutter-cms) originally developed by @lnaden and now extensively improved by [MolSSI](http://molssi.org). Hundreds of open source CMS projects use this structure now, so it is very familiar to many developers and makes it easier for others to help contribute time to help maintain OpenMM's CI infrastructure.

**Comment by peastman** [comment]
This is getting close to being complete.  I still have a few things to fix, and there's more code I might merge in future PRs, like the RPMD plugin.  According to Github, there are 18,908 lines added and 32,017 lines deleted in 210 files, so looking over everything might take a little while. :)  But if you want an overview of the changes, take a look at the new section in the developer guide.  Search for developer.rst in the list of changes.

**Comment by peastman** [comment]
run jenkins

**Comment by peastman** [comment]
@swails any idea why jenkins isn't running?

**Comment by peastman** [comment]
All tests are passing on Travis and AppVeyor (though AppVeyor times out, as usual).  Jenkins isn't running, but I ran all the CUDA and OpenCL tests locally.  So unless someone objects, I'm going to go ahead and merge this.

**Comment by andysim** [comment]
-13,000 LoC!  I've always had issues with OpenCL tests failing on my MacOS laptop, so I'm curious to see if these changes help.  I think this one is ready to go, and a huge improvement, regardless of the outcome of those tests.  Excellent idea and execution 😃

**Comment by swails** [comment]
run jenkins

**Comment by swails** [comment]
I triggered it by hand. I moved Jenkins to a Linode to improve reliability and availability. We may have to fix some settings. 

It will still use my machines as slaves, but won’t rely on one of them to serve Jenkins.

**Comment by peastman** [comment]
run jenkins

**Comment by peastman** [comment]
Thanks!  And it caught a bug that was missed in my local testing.  Could you trigger it again?

**Comment by peastman** [comment]
And it is merged!  Hopefully I didn't break too many things in the process.  Keep an eye out for anything that isn't working.

**Comment by tristanic** [comment]
Holy cow. @peastman, you're a machine!

**Pull request merged**
