### PR TITLE
Catch exception when an OpenCL platform has no devices

### LINKED ISSUE #2541: OpenCL fails in newer Fedora distros
Just updated my laptop (with GTX 1070) to Fedora 31 (since 29 is already EOL - sigh...) and ran into trouble starting simulations on the OpenCL platform (also had the same issue when I upgraded to 29, for the record):

```
  File "/opt/UCSF/ChimeraX-daily/lib/python3.7/site-packages/simtk/openmm/app/simulation.py", line 105, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
  File "/opt/UCSF/ChimeraX-daily/lib/python3.7/site-packages/simtk/openmm/openmm.py", line 11125, in __init__
    this = _openmm.new_Context(*args)
Exception: Error initializing context: clGetDeviceIDs (-1)

Exception: Error initializing context: clGetDeviceIDs (-1)
```
Turns out the problem is that these newer distros all seem to have mesa-libOpenCL installed by default - uninstalling it fixes the issue. But I'm wondering if your OpenCL code could catch the error and simply step on to the next platform (which in my case would have been the correct CUDA one)?

### PR DESCRIPTION
**Pull request by peastman**
Fixes #2541.

@tristanic could you test this and see if it works for you?

### CODE REVIEW

**Comment by tristanic** [comment]
Will give it a try tomorrow.

**Comment by swails** [comment]
Here are some of the Jenkins-reported errors:

```
The following tests FAILED:
	 96 - TestCudaCustomNonbondedForceSingle (Child aborted)
	 97 - TestCudaCustomNonbondedForceMixed (Child aborted)
	 98 - TestCudaCustomNonbondedForceDouble (Child aborted)
	102 - TestCudaDispersionPMESingle (Timeout)
	104 - TestCudaDispersionPMEDouble (Timeout)
	385 - TestCudaRpmdSingle (Failed)
Errors while running CTest
Test project /iscratch/jenkins-cuda/workspace/openmm_openmm_PR-2542
    Start  96: TestCudaCustomNonbondedForceSingle
    Start  97: TestCudaCustomNonbondedForceMixed
1/4 Test  #96: TestCudaCustomNonbondedForceSingle ...Child aborted***Exception:  36.52 sec
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error deleting array param1: CUDA_ERROR_ILLEGAL_ADDRESS (700)
    Start  98: TestCudaCustomNonbondedForceDouble
2/4 Test  #97: TestCudaCustomNonbondedForceMixed ....Child aborted***Exception:  49.64 sec
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error deleting array param1: CUDA_ERROR_ILLEGAL_ADDRESS (700)

    Start 385: TestCudaRpmdSingle
3/4 Test  #98: TestCudaCustomNonbondedForceDouble ...Child aborted***Exception:  42.20 sec
terminate called after throwing an instance of 'OpenMM::OpenMMException'
  what():  Error deleting array param1: CUDA_ERROR_ILLEGAL_ADDRESS (700)
```

Any idea what this is about?

**Comment by peastman** [comment]
No idea.  It's definitely not related to this change, since this PR only affects the OpenCL platform.  For a while the jenkins CUDA builds were just hanging, so I stopped paying attention to them.  For example, [here's one](https://jenkins.jasonswails.com/blue/organizations/jenkins/openmm%2Fopenmm/detail/PR-2524/1/pipeline/8) from a couple of weeks ago that ended with this error:

```
Cannot contact Batwoman-cuda: hudson.remoting.ChannelClosedException: Channel "hudson.remoting.Channel@221fc7f3:Batwoman-cuda": Remote call on Batwoman-cuda failed. The channel is closing down or has closed down
Could not connect to Batwoman-cuda to send interrupt signal to process
```

I have no idea what that means, but I was pretty sure it wasn't connected to OpenMM. :)  I'll go through more of the past builds and see if I can identify a window when this error started happening.

**Comment by swails** [comment]
I was running into some stability problems with one of the build agents.  I removed the GPU that was causing issues on the one slave node and moved the Jenkins hosting to the cloud (GPU agents still run locally, but do so through a Docker container to make the builds more portable between slave agents).

It's been a lot more stable since then (there are currently 3x GTX 780 GPUs in two different slave nodes).

Short story -- the builds should be a lot more stable now.

**Comment by peastman** [comment]
I haven't been able to reproduce the failure.  I tried running that test through both cuda-memcheck and valgrind, but neither found any problems.

Looking back at past PRs, jenkins was passing through #2472.  Starting with #2475 on Nov. 18 jenkins didn't run at all.  It started running again with #2529 on Jan. 16, and this test was failing.  That might be because of a code change in between, or it might be because of a change to the build environment.  Looking at the code changes in between, there were a lot of small changes and one very very big one (#2488).  If something introduced an error, that's by far the most likely one.

**Comment by tristanic** [comment]
Looks good - built with the Fedora 31 GCC (9.2.1), and all the OpenCL tests are passing.

**Comment by tristanic** [comment]
... except for these:
```
       Start 102: TestOpenCLDeviceQuerySingle
102/270 Test #102: TestOpenCLDeviceQuerySingle .....................Child aborted***Exception:   0.50 sec
        Start 103: TestOpenCLDeviceQueryMixed
103/270 Test #103: TestOpenCLDeviceQueryMixed ......................Child aborted***Exception:   0.45 sec
        Start 104: TestOpenCLDeviceQueryDouble
104/270 Test #104: TestOpenCLDeviceQueryDouble .....................Child aborted***Exception:   0.47 sec
```
Looks like they just need the same `try...catch` block?

**Comment by peastman** [comment]
Thanks!  I just made the same change to that file.

**Pull request merged**
