### PR TITLE
Made ComputeContext worker threads rethrow encountered exceptions into the main thread.

### PR DESCRIPTION
**Pull request by Dann239**
While trying to debug the #3039 i ran into a problem: when i tried to catch crashes from main, the exception just "ignored" the catch statement. It puzzled me for a while and after some thinking i realized what the problem was: when an exception arises inside of a worker thread, it crashes the entire thing. So i made it stash the exception until the `flush()` is called and then rethrow it into the main thread.

### CODE REVIEW

**Comment by peastman** [comment]
I like this idea.  We need to think about the implementation a bit.  First I need to clarify something: the title of the PR says it's a change to ThreadPool, but actually you changed the ComputeContext worker thread.  That's not the same thing, and it's used for a lot fewer purposes than ThreadPool.  Which one did you intend to change?

**Comment by Dann239** [comment]
My bad, got my terminology mixed up. I amended the commit message and the PR title, i indeed only intended to change the ComputeContext worker threads.

**Comment by peastman** [comment]
That simplifies things a lot.  The only thing that thread is ever used for is parallelizing a computation across multiple GPUs.  There's a separate ComputeContext for each GPU, and each one has its own worker thread.

This code looks good.  The one thing I'd change is the terminology, which is misleading.  Throwing an exception is not a crash.  It's just an exception, which can potentially be caught and handled property.  So I would rename "crashed" to "threwException" and "crash" to "exception".

Also one very minor bit of formatting.  When a language keyword (if, while, etc.) is followed by an expression in parentheses, there should be a space in between.  So `catch (const OpenMMException& e)`, not `catch(const OpenMMException& e)`, and so on.

**Comment by Dann239** [comment]
@peastman : i did what you suggested, please verify that i haven't missed anything.

**Comment by peastman** [comment]
Looks good.  Thanks so much for this change, and congratulations on your first merged PR!

**Pull request merged**
