### PR TITLE
Set ARCHIVE destination so that OpenMM.dll ends up at the correct place

### PR DESCRIPTION
**Pull request by isuruf**
Also use GNUInstallDirs

Should fix https://github.com/conda-forge/openmm-feedstock/pull/67

### CODE REVIEW

**Comment by peastman** [comment]
Thanks!  Can you explain what this is doing, and what changed in the last week that caused it to break between the release candidate and the release?  And why did it break only on Windows, and only on Python 3.9, but not any other version?

We've already gone through our release candidate process and made the release on Github.  If we make a change like this to the build scripts at this point, we'll need to pull the Github release, do a new release candidate, and put off the release for another week.

**Comment by isuruf** [comment]
There was a change in how DLLs are loaded in python 3.8 and we reverted that change in conda to avoid breaking software.
This was meant to be a temporary workaround and we've finally reverted that in 3.9.9 and 3.10.0.
See https://github.com/conda-forge/python-feedstock/pull/481#discussion_r716153174

**Comment by peastman** [comment]
Does that mean all existing OpenMM releases just stopped working on Python 3.9?

**Comment by isuruf** [comment]
Yes. A user can set `CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1` or we can hotfix older packages by adding a `python <3.9.9` condition at https://github.com/conda-forge/conda-forge-repodata-patches-feedstock

**Comment by peastman** [comment]
This only applies to Windows, right?  Is there a way we can put that constraint into meta.yaml for the new version so we don't need to pull the release?

**Comment by peastman** [comment]
Will we get the correct behavior if I list the dependency as

```
- python <3.9.9  # [win]
```

in the `host` and `run` sections?

**Comment by peastman** [comment]
We should finish this up so we can add Python 3.10 support.  CI is showing a bunch of failures, but with several of them I can't tell what's failing.  Everything in the log looks ok, but it still reports an error.

**Comment by peastman** [comment]
This is superseded by #3473.

**Comment by jchodera** [comment]
@peastman: Can you articulate why #3473 is the superior solution to this PR?

**Comment by peastman** [comment]
Either one of them can fix the problem.  #3473 just does it more simply, and allowing us to maintain the same library layout on all platforms.  Also, it's a direct fix for the thing that broke.  We were already adding the correct directory to the library path, but in Python 3.10 the mechanism for doing that changed.  So it just switches from the old mechanism to the new one.

**Pull request closed without merging**
